update_data:
  name: 전체 데이터 갱신
  description: "선택된 도시가스 공급사 웹사이트에서 평균열량 및 열량단가 데이터를 모두 새로고침합니다."

update_price_data:
  name: 열량단가 갱신
  description: "선택된 도시가스 공급사 웹사이트에서 최신 열량단가 데이터를 가져와 반영합니다."

update_heat_data:
  name: 평균열량 갱신
  description: "선택된 도시가스 공급사 웹사이트에서 최신 평균열량 데이터를 가져와 반영합니다."

update_base_fee:
  name: 기본요금 갱신
  description: "선택된 도시가스 공급사 웹사이트에서 기본요금 및 기타 설정값을 조회하여 반영합니다."

